[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['corepack enable', 'corepack prepare pnpm@9.1.0 --activate', 'pnpm install --filter=web...']

[phases.build]
cmds = ['pnpm --filter=web build']

[start]
cmd = 'cd apps/web && node .next/standalone/apps/web/server.js'
