[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile --filter=@themis/api..."
]

[phases.build]
cmds = [
  "cd apps/api",
  "pnpm prisma generate",
  "pnpm build"
]

[start]
cmd = "cd apps/api && npx prisma migrate deploy && node dist/main.js"
